### ISSUE TITLE
Stylus

### ISSUE THREAD

**Issue by qiuxiang** [qiuxiang/qiuxiang#15]
```css
code, pre, .blob-code-inner {
  font-family: monospace !important;
}
*::-webkit-scrollbar {
  display: none;
}
#terminal-container .terminal {
  padding: 0;
  height: 100%;
}
#terminal-container {
  width: calc(100% + 16px);
  position: fixed;
}
```
